---
- hosts: all
  become: yes
  vars_files:
    - ./server_vars.yml
  vars:
    jar: 'java-1.0-SNAPSHOT.jar'
  tasks:
    - name: dir exists
      file: path=/aazhogov/ state=directory
    - name: copy jar
      copy:
        src: './../java/target/{{ jar }}'
        dest: '/aazhogov/{{ jar }}'
        mode: '0755'
    - name: run jar
      shell: java -jar /aazhogov/{{ jar }} > /aazhogov/result.txt
    